//
// Generated file, do not edit! Created by nedtool 5.6 from ibanPaquete.msg.
//

#ifndef __IBANPAQUETE_M_H
#define __IBANPAQUETE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>ibanPaquete.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet IbanPaquete
 * {
 *     double initTime;
 *     double nodeInitTime;
 *     long hopNum = 0;
 *     int src;
 * 
 * }
 * </pre>
 */
class IbanPaquete : public ::omnetpp::cPacket
{
  protected:
    double initTime;
    double nodeInitTime;
    long hopNum;
    int src;

  private:
    void copy(const IbanPaquete& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IbanPaquete&);

  public:
    IbanPaquete(const char *name=nullptr, short kind=0);
    IbanPaquete(const IbanPaquete& other);
    virtual ~IbanPaquete();
    IbanPaquete& operator=(const IbanPaquete& other);
    virtual IbanPaquete *dup() const override {return new IbanPaquete(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getInitTime() const;
    virtual void setInitTime(double initTime);
    virtual double getNodeInitTime() const;
    virtual void setNodeInitTime(double nodeInitTime);
    virtual long getHopNum() const;
    virtual void setHopNum(long hopNum);
    virtual int getSrc() const;
    virtual void setSrc(int src);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IbanPaquete& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IbanPaquete& obj) {obj.parsimUnpack(b);}


#endif // ifndef __IBANPAQUETE_M_H

